### ISSUE TITLE
Support optional time in Old Admin

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#148]
Update the old admin tool to support the new optional time feature in the API.

## Test Case
1. Create a single date event with no end time --> save and publish to check that the date is persisted without time
1. Create an event with a date range with and end date 4 days after the start date, no time in the start date and no time in the end date --> Check that the end date is persisted without time.
1. Create a daily recurring event across 2 weeks without a start time --> check that the recurring event is persisted
2. Create an event with custom dates without start times --> check that the custom dates are persisted

**Comment by saumier** [comment]
@troughc Please review recurring dates with and without end time. There were a lot of changes made to support optional start time and end time. Thx. You can test in staging or production.

**Comment by troughc** [comment]
I can't seem to publish my new event - see screenshot for what i put in @saumier. Everytime I try to publish the event disappears from the lis t view and I have to back up to it (I cannot search for it. 

![Image](https://user-images.githubusercontent.com/64489312/212740370-aeb3fa56-3398-4aa2-90f9-ec78f608212c.png)

**Comment by troughc** [comment]
Bug discovered @SuhailAliyar - the event backs up a day every time i save. This event was originally set to december 18 with NO  starttime.  I saved it several times and it backed up a day each save until January 15 (see screenshot).

**Comment by SuhailAliyar** [comment]
@troughc Seems like this issue is fixed. I couldn't reproduce this issue.

**Comment by troughc** [comment]
This is likely a timezone issue.

**Comment by troughc** [comment]
Test on Chrome: @SuhailAliyar @saumier  See use case 3. There is a bug. Thanks!
FIXED: Date without a start time no longer backs up a day every time i save/update.  Yay!
Testing Gregory's test case
1. Tested with http://staging.oldcms.footlight.io/admin/add-event/?id=63c58e49462621006faa71b5   PASS
2.Tested with http://staging.oldcms.footlight.io/admin/add-event/?id=63c8019daf12160070814dea     PASS
3. Tested with http://staging.oldcms.footlight.io/admin/add-event/?id=63c803f7af12160070814f91.     FAILED - a start-time was automatically added (see screenshot). 
 Steps to repeat:

1. create a recurring daily event and add all required fields (no start time).
2. Only the Save button is available (no Publish button). Forced to click Save- user is taken to event listing page.
3. Re-enter the event you just created. The current time has been added to the start time field and the Publish button is available. 
4. You could publish, then reenter evnet and try removing the starttime and clicking Update (nothing will happen of course).

End of test






![Image](https://user-images.githubusercontent.com/64489312/213203116-8ea61ff0-f8f1-4da7-8167-bbc3d817be76.png)

**Comment by saumier** [comment]
@troughc Back to you!

**Comment by troughc** [comment]
Test case 3 - the Publish button is now there, however, when I click it, nothing happens - I still cannot publish. See http://staging.oldcms.footlight.io/admin/add-event/?id=63cf0b8238256900709c49ec

Test case #4 - the event disappears when I click save. I tried to create "La route de rire" event twice using custom dates. It seemed to accept the dates (See screenshot with 4 dates). Then, when I click save, it says that the event is created successfully, but it isn't there. @saumier 


![Image](https://user-images.githubusercontent.com/64489312/214164418-a33f52e6-6f96-4cb4-8a6b-91c762d0866f.png)

**Comment by saumier** [comment]
@SuhailAliyar I am also able to recreate this bug with a single date as follows:
1. Create a new event
2. Click recurring dates
3. Click customize
4. Enter a date
5. Save - event disappears

**Comment by SuhailAliyar** [comment]
The issue with custom date recurring events is fixed.

**Comment by troughc** [comment]
Test case 4: PASS - I was able to create this theatre event (ART) with custom dates: http://staging.oldcms.footlight.io/admin/add-event/?id=63cfd74137d0fc00707ad3c0
